resolver: nightly-2017-12-16

packages:

# e.g. a local filepath
- ./

# e.g. a url to a `.tar.gz`
# - https://example.com/foo/bar/baz-0.0.2.tar.gz

# e.g. a git repo and commit
- location:
    git:    https://github.com/sboosali/spiros
    commit: 0c5f3584e73ae3e4c00b0a142d2024c241ac3032
  extra-dep: true

# e.g. a "megarepo" with individual packages in subdirectories 
- location:
    git:    https://github.com/sboosali/enumerate
    commit: a7b28ef6db976bbf6643e0437670fe371f13b754
  subdirs:
  - enumerate
  - enumerate-function  
  extra-dep: true

extra-deps: 
# - spiros-0.0.0
- direct-murmur-hash-1.0.1
- generic-lens-0.5.0.0
